### ISSUE TITLE
CP-2128 Support bash globbing for entry points

### ISSUE THREAD

**Issue by travissanderson-wf** [Workiva/dart_dev#105]
This might just get closed as "Won't Fix" but we have a somewhat strange library where we currently run dartanalyzer against the usual entry points and then also `lib/external/**/*.dart`.  dart_dev fails because that isn't a file, but it resolves to files via bash [globbing](http://tldp.org/LDP/abs/html/globbingref.html) (I think I am using the right term there but not 100% sure!).

**Comment by christopherdaly-wf** [comment]
Looks like a library for globbing exists
https://github.com/dart-lang/glob

**Comment by maxwellpeterson-wf** [comment]
This will be addressed with Dart 2.0's analyzer config
