### ISSUE TITLE
CP-2124 Better test debugging: support `--pause-after-load` 

### ISSUE THREAD

**Issue by greglittlefield-wf** [Workiva/dart_dev#120]
The `test` package provides a `--pause-after-load` flag (see https://github.com/dart-lang/test#debugging) that pauses the tests before they run, providing an opportunity to open the debugger.

Consumers of `dart_dev` should be able to take advantage of this option somehow.

Perhaps the `dart_dev test` command's CLI could be refactored to forward any extra arguments to the `test` package's CLI?

**Comment by timmccall-wf** [comment]
@evanweible-wf @greglittlefield-wf Is this one dead? Can we get it in? @patkujawa-wf just recently had a use for this.

**Comment by timmccall-wf** [comment]
Oh shoot, I thought this was PR. Didn't see it was an issue.
