### ISSUE TITLE
CP-2123 Coverage: Hangs on skipped tests

### ISSUE THREAD

**Issue by davidmarne-wf** [Workiva/dart_dev#121]
Steps to reproduce:
add the skip: true to all tests

```
group('Some Group', () {
    setUp(() async {
      reactClient.setClientConfiguration();
    });

    test('Some Test', () async {}, skip: true); 
  });
```

run the coverage reporter

```
pub run dart_dev coverage --no-html
```

The coverage report will hang after running the tests for the file and before collecting coverage for the file

**Comment by markcampanelli-wf** [comment]
I think this may have been fixed. Skipping with coverage is working in 1.1.1.
