### ISSUE TITLE
Error thrown when attempting to run Dart_Dev Test with specific test file path included

### ISSUE THREAD

**Issue by philipbalvanz-wf** [Workiva/dart_dev#138]
The readme states "Individual test files can be executed by appending their path to the end of the command." but it appears this may not be working anymore as I get the following error when I attempt to do so.  The test passes if run by name or as part of the whole package, so it isn't an issue with the test itself.

![Image of error](http://content.screencast.com/users/Philip.Balvanz/folders/Jing/media/511b3fe6-8131-452c-815c-302e04050af7/00001357.png)
http://screencast.com/t/WiKRrhC0c

**Comment by evanweible-wf** [comment]
@philipbalvanz-wf dart_dev only handles running the tests, so if it's correctly running the individual file that you specified, I would think that it's working. Is it possible that there's some setup that is happening at a higher level when the entire test suite runs that doesn't occur when the individual test file runs by itself?

If you could point me to the project and a branch, I'd be glad to check it out.

**Comment by jayudey-wf** [comment]
it looks like after the latest update that test files are no longer being run in isolation if passed into the `test task`, which I think is the crux of what @philipbalvanz-wf reported

```
LS2-2:taxonomy-analyzer jayudey$ ddev test test/unit/language_test.dart -p content-shell

::: pub get
    Resolving dependencies...
    Warning: You are using these overridden dependencies:
    ! http_parser 2.1.0
    ! truss 1.4.4 from git git@github.com:Workiva/truss.git at e5d7d4
    Got dependencies!
Ignoring unknown argument
Ignoring unknown argument

::: pub serve --port=0 test
    Loading source assets...
    Loading sass, web_skin_dart and test/pub_serve transformers...
    Serving taxonomy_analyzer test on http://localhost:60300

::: pub run test --concurrency=4 -p vm -p content-shell --reporter=expanded --pub-serve=60300 test/unit/language_test.dart test/unit/
```

note that `test/unit/` is still being added to the task, the -n param is still working as expected however
