### ISSUE TITLE
CP-2119 coverage task ignores test file/directory paths

### ISSUE THREAD

**Issue by markcampanelli-wf** [Workiva/dart_dev#144]
It would be great if the coverage task could take the same optional test file/directory paths that the test task can take. Our use case is that we would like to use a test runner for only the coverage task, but otherwise default to `config.test..unitTests = ['test/unit']` in dev.dart. This would avoid sharing so much state when we run the test task vs. the coverage task. It might also be nice to specify a different `..unitTests =` for the test vs. coverage tasks. Currently, we use `config.test..unitTests = ['test/test_suite_runner_test.dart']`, which apparently applies to both coverage and test.

The reason we use a test runner is that the coverage task is otherwise VERY slow, apparently starting up a new pub serve instance for each group of tests that it finds in the search path.

**Comment by maxwellpeterson-wf** [comment]
> The reason we use a test runner is that the coverage task is otherwise VERY slow, apparently starting up a new pub serve instance for each group of tests that it finds in the search path.

This has been fixed via the `gen-test-runner` task.
