### ISSUE TITLE
CP-2118 Report build status to Sauce Labs

### ISSUE THREAD

**Issue by greglittlefield-wf** [Workiva/dart_dev#154]
The Sauce Labs task locally reports which builds have passed/failed, but doesn't update the status on Sauce Labs.

The status can be updated after a build completes via a REST call:
https://wiki.saucelabs.com/display/DOCS/Annotating+Tests+with+the+Sauce+Labs+REST+API

**Comment by evanweible-wf** [comment]
Saucelabs task was removed in v2. If we choose to reimplement it in a general way, it will most likely be via a separate package.
