### ISSUE TITLE
CP-2117 Generate HTML test files for saucelabs task

### ISSUE THREAD

**Issue by jayudey-wf** [Workiva/dart_dev#155]
Currently a user needs to specify an html file in order to utilize the `saucelabs` tasks. 

If a test file doesn't need to have specific imports in its companion html file the test runner takes care of it by generating an empty html file, because of this the test creator most likely will not create a companion html file for the test. Having to create unnecessary html files adds additional effort for consumers, dart_dev should be able to recognize if an html file is needed and generate it as part of the task.

**Comment by evanweible-wf** [comment]
Saucelabs task was removed in v2. If we choose to reimplement it in a general way, it will most likely be via a separate package.
