### ISSUE TITLE
CP-2115 Add a check flag to gen-test-runner

### ISSUE THREAD

**Issue by bencampbell-wf** [Workiva/dart_dev#159]
It is possible for the test runner to exclude tests because they generated test runner has not been updated to include it. As a developer I would like to be able to add a dart_dev command in my CI process to confirm the generated test runner does not need to be updated; Simliar to how `dart_dev format --check`. This would allow the CI process to fail in the event a test is not being run.

**Comment by maxwellpeterson-wf** [comment]
Done
