### ISSUE TITLE
WP-4331 CP-2567 V2: coverage

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#174]
## `ddev coverage`

TODO

**Comment by rmconsole2-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/174/addTicketToTitle'>here</a> to have Rosie create one for you.
