### ISSUE TITLE
WP-4288 CP-2570 V2: gen-test-runner

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#177]
## `ddev gen-test-runner`

TODO

**Comment by rm-astro-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/177/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by evanweible-wf** [comment]
Generated test runner support removed from ddev in v3, and no plans to re-add it.
