### ISSUE TITLE
WP-4366 CP-2977 V2: sort-pubspec

### ISSUE THREAD

**Issue by dustinlessard-wf** [Workiva/dart_dev#193]
## `ddev sort-pubspec`

This task alphabetizes each group in a pubspec.yaml file.

### Package Configuration

There won't be any additional configuration for this specific task, but it will be disabled by default and enabled by adding a configuration entry in the  `dart_dev.yaml` file:

``` yaml
sort-pubspec:true
```

### Command Line Configuration

There aren't any command line options at this point.

```
$ pub run dart_dev sort-pubspec -h

Usage: pub run dart_dev sort-pubspec 
```

### `--check`

Similar to the `format` task, we need to support a `--check` flag that will run the task without actually making any changes and exit with a non-zero code if there are changes that would have been made.

### Task List
- [ ] **`dart_dev.yaml` configuration**
- [ ] **Implement help/usage output (see above)**
- [ ] **`--check`**

**Comment by rmconsole2-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/193/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by evanweible-wf** [comment]
No plans to support this at this time.
