### ISSUE TITLE
CP-3228 Use test runner when collecting coverage

### ISSUE THREAD

**Issue by greglittlefield-wf** [Workiva/dart_dev#200]
When running tests coverage, platform selectors don't work as expected since the `test` runner isn't being used.

E.g., tests with `testOn: !content-shell` still run during coverage.

Now that https://github.com/dart-lang/test/issues/36 isn't blocked, this should be possible.

**Comment by rmconsole3-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/200/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by evanweible-wf** [comment]
Awesome! Thanks for the heads up @greglittlefield-wf. I'll try to roll this in to V2 with the rewrite of the coverage task.

**Comment by greglittlefield-wf** [comment]
This also prevents us from using test tags, which seem to be the most promising way so far to run certain tests conditionally based on whether you're in the DDC: https://github.com/dart-lang/test/issues/652

**Comment by maxwellpeterson-wf** [comment]
@greglittlefield-wf could you clarify this part: `Now that dart-lang/test#36 isn't blocked, this should be possible.`

@evanweible-wf

**Comment by greglittlefield-wf** [comment]
@maxwellpeterson-wf I think when I created this issue, it seemed possible to be able to hook coverage and the test runner together with some observatory/isolate magic.

However, based on this comment: https://github.com/dart-lang/test/issues/36#issuecomment-284563366
> I agree that the best approach here is for `test` to be involved in coverage collecting—that's the best way to ensure a smooth user interface and to avoid dependencies on `test`'s internal structure, which is not a guaranteed stable interface.

it seems like it's probably best to rely on changes in `test` to facilitate coverage collection.

**Comment by evanweible-wf** [comment]
Coverage collection through the test runner is in progress, so this should no longer need to be a ddev concern.
