### ISSUE TITLE
CP-3313 --check should verify contents of generated HTML for gen-test-runner task

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#203]
--check should verify contents of generated HTML for gen-test-runner task

**Comment by rmconsole2-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/203/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by evanweible-wf** [comment]
Our recommendation is to no longer use generated test runners, and as such v3 has removed the `gen-test-runner` task. The original impetus was to speed up full test runs by only having to load one (or a few) test suites, but the startup time for individual test files has improved since then (probably ~3 years ago) and this is no longer as much of a concern. Additionally, treating every test file as its own suite has the advantage of being able to run each test file on its own (IDEs now support doing this directly from the test file) and allows us to leverage features like build_runner's `--build-filter` for large projects to speed up rebuild time when iterating on a subset of tests.

There was one particularly useful feature of generated test runners, which was being able to share an HTML file – you wouldn't have to litter your `test/` directory with an HTML file for every test that requires it (common with over_react consumers). The `test_html_builder` package was created to serve this specific use case: https://pub.dev/packages/test_html_builder
