### ISSUE TITLE
WP-3990 CP-3341 hasImmediateDependency() fails for pubspec.yaml with empty "dependencies" map

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#206]
```yaml
dependencies:
dev_dependencies:
  browser: ^0.10.0+2
```

The above will cause `hasImmediateDependency()` to fail with this:

```
Unhandled exception:
NoSuchMethodError: The getter 'keys' was called on null.
Receiver: null
Tried calling: keys
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      StandardPlatformUtil.hasImmediateDependency 
```

Reported by @dustinlessard-wf

**Comment by rm-astro-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/206/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by markerickson-wf** [comment]
I ran into this bug today

**Comment by evanweible-wf** [comment]
Fixed in v3.
