### ISSUE TITLE
WP-3786 Tests for onError handlers in the Reporter

### ISSUE THREAD

**Issue by jayudey-wf** [Workiva/dart_dev#210]
Add tests for https://github.com/Workiva/dart_dev/pull/209

**Comment by rm-astro-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/210/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by evanweible-wf** [comment]
Obviated with v3.
