### ISSUE TITLE
WP-3794 Full depth traversal option

### ISSUE THREAD

**Issue by markcampanelli-wf** [Workiva/dart_dev#217]
It would be great to be able to specify a full depth traversal option in the tooling, such as for directories to run the analyzer on.

Go's use of ./... to signify this is really convenient, for example.

**Comment by rm-astro-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/217/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by evanweible-wf** [comment]
For analysis, this is supported via `dartanalyzer .`. In ddev v3, the `AnalyzeTool` offers further configuration options.
