### ISSUE TITLE
WP-4856 Ability to specify web-compiler flag Pub server spun up by ddev test

### ISSUE THREAD

**Issue by greglittlefield-wf** [Workiva/dart_dev#234]
It would be useful to be able to run tests in the Dart Dev Compiler while still taking advantage of the way dart_dev spins up a Pub server.

If I could do `ddev test --web-compiler=dartdevc` for CI purposes, that would be awesome.

**Comment by rmconsole-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click a type to create one automatically: <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/234/addTicketToTitle/Task/">Task</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/234/addTicketToTitle/Bug/">Bug</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/234/addTicketToTitle/Improvement/">Improvement</a>

**Comment by maxwellpeterson-wf** [comment]
Fixed in #235
