### ISSUE TITLE
WP-4900 Passing options to `pub run test` requires manually specifying test files

### ISSUE THREAD

**Issue by greglittlefield-wf** [Workiva/dart_dev#236]
I want to be able to exclude some tests via a tag, without having to specify all my tests manually. Currently, that isn't possible,
For example:
* Input:
    ```bash
    ddev test
    ```
    Command used:
    ```
    pub run test --concurrency=1 -p vm -p content-shell --reporter=expanded --pub-serve=49392 test/vm_tests/ test/toolbars_test.dart test/ui_components_1_test.dart test/ui_components_2_test.dart test/ui_form_components_1_test.dart test/ui_form_components_2_test.dart test/ui_form_components_3_test.dart test/ui_core_test.dart test/wdesk_util_test.dart test/doc_utils_test.dart
    ```
* Input:
    ```bash
    ddev test -- -x no-ddc
    ```
    Command used (note how no test files are specified):
    ```
    pub run test --concurrency=1 -p vm -p content-shell --reporter=expanded --pub-serve=65256 -x no-ddc
    ```

**Comment by rmconsole2-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click a type to create one automatically: <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/236/addTicketToTitle/Task/">Task</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/236/addTicketToTitle/Bug/">Bug</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/236/addTicketToTitle/Improvement/">Improvement</a>

**Comment by maxwellpeterson-wf** [comment]
Fixed in https://github.com/Workiva/dart_dev/pull/235

**Comment by greglittlefield-wf** [comment]
@maxwellpeterson-wf I don't think this was fixed in that PR; I'm still seeing this issue in dart_dev 1.8.0.

**Comment by greglittlefield-wf** [comment]
I think https://github.com/Workiva/dart_dev/issues/234 was the one that was supposed to be closed.

**Comment by maxwellpeterson-wf** [comment]
Oops, my bad!

**Comment by evanweible-wf** [comment]
Fixed in v3. Default test paths can be configured in `dart_test.yaml`. Args can be passed to the test process via `ddev test --test-args="..."`. The statically configured test paths can be overridden by passing paths to the test command: `ddev test test/foo_test.dart test/bar/`.
