### ISSUE TITLE
dart_dev coverage is not running with checked mode enabled

### ISSUE THREAD

**Issue by kezhuw** [Workiva/dart_dev#245]
See https://github.com/dart-lang/test/commit/52e08c951814fbc07ec505fa28cc3b1c69fe0147 (Always run tests in checked mode. )

dart_dev coverage actually run test to collect coverage, it should be consistent to standard behavior.

**Comment by rmconsole2-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click a type to create one automatically: <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/245/addTicketToTitle/Task/">Task</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/245/addTicketToTitle/Bug/">Bug</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/245/addTicketToTitle/Improvement/">Improvement</a>

**Comment by evanweible-wf** [comment]
@kezhuw we do need to make sure that we're running the tests in checked mode during `dart_dev coverage`, but unfortunately as far as making the test running consistent between test and coverage, we'll have to wait for coverage support in the `test` package itself: https://github.com/dart-lang/test/issues/36

**Comment by greglittlefield-wf** [comment]
This should be able to be accomplished by:
- adding the `--checked` argument to the `dart` process in `_runTestOnVm`
- adding the `DART_FLAGS=--checked` environment variable to the `content_shell` process in `_runTestInBrowser`

Semi-related, using `pub run coverage:run_and_collect` for coverage >=[0.9.0](https://github.com/dart-lang/coverage/blob/master/CHANGELOG.md#090---2017-01-11) uses checked mode.

**Comment by evanweible-wf** [comment]
I don't think checked mode is relevant anymore on dart 2, and dart_dev v3 is only going to support dart 2. Additionally, coverage collection will soon be possible via the test runner which means dart_dev no longer needs its own, separate `coverage` task.
