### ISSUE TITLE
WP-5676 Intermittent failures in CI with ` pub run dart_dev format --check`

### ISSUE THREAD

**Issue by markcampanelli-wf** [Workiva/dart_dev#247]
Our CI (Smithy) fails every once in a while with the following:
```bash
[38;5;3m[38;5;6m
::: Failure output: One of your subtasks exited with a non-zero exit code. See the output below for more information:
[38;5;3m    The command, pub run dart_dev format --check, contained this in the stderr; 
    [38;5;6m
    ::: dart tool/over_react_format/format_task.dart --check
        Loading `format` config from dart_dev...
    
     
    [38;5;3m    [38;5;1mPackage "dart_dev" must be an immediate dependency in order to run its executables.
    [38;5;1mdart tool/over_react_format/format_task.dart --check failed.
    
[38;5;1mSome task failed: pub run dart_dev format --check
```

**Comment by rmconsole3-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click a type to create one automatically: <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/247/addTicketToTitle/Task/">Task</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/247/addTicketToTitle/Bug/">Bug</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/247/addTicketToTitle/Improvement/">Improvement</a>

**Comment by evanweible-wf** [comment]
I _think_ this was related to a race condition that was fixed by @greglittlefield-wf's patch to the `pub` client on Dart 2. I'm going to close, but if it comes up again, feel free to re-open.
