### ISSUE TITLE
WP-5770 Ability to generate HTML companion files for each individual test suite

### ISSUE THREAD

**Issue by greglittlefield-wf** [Workiva/dart_dev#248]
For codebases with a large amount of tests, a single test file that aggregates many suites, like the one produced by `gen-test-runner`, can take a very long time to load (can be up to several minutes).

These long load times increases the time it takes even to run a subset of tests locally, which can be very frustrating to work with (filtering tests using `-n`/etc. still loads all the suites but filters them at runtime).

For many repos, browser tests cannot be run without a corresponding `.html` that sets up other scripts, so the single aggregated test suite generated by `gen-test-runner` is the only option.

We should add functionality to generate individual `.html` companion files for each suite, which will allow these suites to be run more quickly when developing.

We do this generation in one of our repos: https://github.com/Workiva/web_skin_dart/blob/2.14.0/tool/generate_individual_test_suites.dart#L66

**Comment by rmconsole-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click a type to create one automatically: <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/248/addTicketToTitle/Task/">Task</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/248/addTicketToTitle/Bug/">Bug</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/248/addTicketToTitle/Improvement/">Improvement</a>

**Comment by evanweible-wf** [comment]
This use case has been addressed via the `test_html_builder` package: https://pub.dev/packages/test_html_builder
