### ISSUE TITLE
dart_dev fails for alternative package structure

### ISSUE THREAD

**Issue by dspicher** [Workiva/dart_dev#335]
The check
https://github.com/Workiva/dart_dev/blob/e28758f71557037e165a04a522434d5a5abe0dd7/lib/src/utils/assert_dir_is_dart_package.dart#L8
fails when multiple packages are maintained in a single repository under `packages/<package>`. This is quite common, see e.g. https://github.com/felangel/bloc or https://github.com/rrousselGit/provider.

**Comment by evanweible-wf** [comment]
Hi @dspicher, sorry for the delayed response here. How are you trying to use dart_dev in these repos? At the root, or in each individual `packages/<package>` directory?

**Comment by dspicher** [comment]
I cannot reproduce this anymore, might have been connected to a faulty installation of `dart`. Thanks for following up.
