### ISSUE TITLE
CP-2148 Add --watch flag to analyze, formatter, test

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#38]
Investigate the possibility of adding watchers to tasks that devs might want to run continually (analyze, format, tests).

**Comment by greglittlefield-wf** [comment]
I noticed that Pub servers emit a `Build completed successfully` log when files are changed.

If we wanted to implement a quick-and-dirty watcher for projects that have `pubServe` set to `true`, we could potentially use that log as indicator to rerun the tests.

Just an observation/idea.

**Comment by johnbland-wf** [comment]
In the SOX JS watcher, I found a few messages useful for determining a test run being complete: https://github.com/Workiva/w-js-sox/blob/master/tool/watch.dart#L22-L26.

**Comment by evanweible-wf** [comment]
Moving to a separate issue: https://github.com/Workiva/dart_dev/issues/319
