### ISSUE TITLE
CP-2146 Present this repo on Dart Live

### ISSUE THREAD

**Issue by robbecker-wf** [Workiva/dart_dev#49]
There's a good opportunity to get some exposure for this tooling via presenting it on Dart Live.

**Comment by gjersvik** [comment]
Hi
I am the person that is working on getting a global dart online conference style show of the ground. And my hope its to make the community more transparent and let people see that the dart community is a lot bigger and more diverse than just Google.

The format is doing online whatever would work on a stage. Lighting talks, presentation, demos, panel and q&a shows. At lest now in the beginning i am hands of and try to make it a mostly speaker driven. So the live part will be scheduled at a time that works best for you. Then a later time i will edit one or more together to make show that i put on YouTube and other platforms.

A few suggestion on what i would love to see would be:
* A quick lighting talk style presentation off the dart_dev package. Working on a collection of them as my first episode.
* If Dart is used inside Workiva and that is something someone can talk about i would love a longer segment on that. As that would help dispel the notion that Dart is Google only. Stuff like what Workiva do?, where do you use Dart?, challenges and successes wit dart. Maybe some tips and trick you have learned.
* There have been request about doing a Dart Tooling show at one time in the future. But that has not been fleshed out.

This is not and ether or its more of any all deal. And i am also every open to ideas.

I am hoping to work with you. If not soon maybe later when the show is more establish. Just remember if everyone wait for stable it will never be.
