### ISSUE TITLE
CP-2142 Test task: ability to run a subset of the tests

### ISSUE THREAD

**Issue by maxwellpeterson-wf** [Workiva/dart_dev#55]
I want to be able to run a subset of the tests:

``` bash
$ pub run dart_dev test test/my_module/

$ pub run dart_dev test test/my_module/test_module.dart
```

**Comment by evanweible-wf** [comment]
+1, this can be supported. Also, I want to add support for the test packages `-n` flag which allows you to pass in a string that gets matched against the test names and only matching tests run

**Comment by trentgrover-wf** [comment]
+1 from Tim McCall

**Comment by markerickson-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
Addressed.
