### ISSUE TITLE
CP-2139 New Task: Code Generation

### ISSUE THREAD

**Issue by bencampbell-wf** [Workiva/dart_dev#62]
## Feature Request

As a developer I should be able to execute code generation commands with dart dev. I should be able to define a "library search path" in the configuration that defines all the code paths to apply a [source_gen Generator class](https://github.com/dart-lang/source_gen/blob/master/test/src/comment_generator.dart). I should be able to specify a list of of generator classes that will be applied to the given search path items. When I run `pub run dart_dev generate` the tool should use my configuration for to determine the list of generators and the search paths to generate code.

**Comment by maxwellpeterson-wf** [comment]
@bencampbell-wf does `build` cover your needs now?

**Comment by evanweible-wf** [comment]
We have plans to add a `build` target that proxies `webdev build --[no-]release`, which should cover this case.
