### ISSUE TITLE
Analyze: improve documentation to better explain what "entry points" are and how many are necessary

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#65]
The dartanalyzer follows imports, which means it's only necessary to analyze the top-level entry points since all other files (that are imported) will be reachable and will be analyzed.

On this same note, the "entryPoints" config option may not be very intuitive since it accepts directories or files and expands directories to look for all top-level files. We may want to leave the file expansion to the shell and only accept a list of files.

**Comment by trentgrover-wf** [comment]
analyze didn't find an unused import that I added to a `test/subdir` file that is definitely imported by a file at the `test` level...

**Comment by evanweible-wf** [comment]
> One possible addition that might provide some value would be building a list of all .dart files in a project and comparing that list to the list of files analyzed by dartanalyzer according to the projects dart_dev config. Then we could provide a list of files that weren't analyzed as a warning to the project maintainer
Would help detect entry points that just haven't been defined in the dart_dev config as well as .dart files that may be unused

**Comment by evanweible-wf** [comment]
Should incorporate some of the info from this: https://gist.github.com/evanweible-wf/cd69694cdd062746a6f0ad4c5fbd55b3 into the documentation for `AnalyzeTool` in v3.

**Comment by evanweible-wf** [comment]
This has been simplified with improvements to analyzer.
