### ISSUE TITLE
CP-2151 More intelligent directory support

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#7]
Tasks like `analyze` and `format` currently only target the `lib/` directory by default. This could be made more intelligent by checking for the existence of other standard directories (`bin/`, `example/`, `tool/`) and including them only if they exist.

**Comment by evanweible-wf** [comment]
Additionally, we should check the directories given to tasks like analyze and format to verify that they actually exist. We can display a more helpful error message than a stack trace in those scenarios.

**Comment by markerickson-wf** [comment]
It would be nice if format also formatted your tests in `test/`

**Comment by evanweible-wf** [comment]
This is covered in v3. Default behavior for both analysis and formatting is to operate on the current working directory.
