### ISSUE TITLE
CP-2134 Test: run tests in checked mode

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#74]
There should at least be an option to run tests in checked mode. As tests are currently being run in a separate process using the `pub run test` executable, it would require adding the `-c/--checked` flag to the `pub run` command. If the test task was updated to run tests programmatically, it would probably just inherit the checked flag from the pub run command used to run dart_dev.

**Comment by trentgrover-wf** [comment]
should also be able to run examples with dartium launched in checked mode
