### ISSUE TITLE
Consider renaming the `dev.dart` file to better convey it's purpose as configuration rather than script

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#77]
Possible alternatives:
- `dart_dev_conf.dart`

**Comment by maxwellpeterson-wf** [comment]
+1 `dart_dev_conf.dart` or `dev_conf.dart`

**Comment by travissanderson-wf** [comment]
+1 to dart_dev_conf.dart, slightly verbose name but more clear on what its purpose is.  And you don't really type the name out often anyway.
