### ISSUE TITLE
Analyze task fails on `part` files

### ISSUE THREAD

**Issue by trentgrover-wf** [Workiva/dart_dev#86]
Tim McCall:
We are having some problems with the ddev analyze task. The analyzer cannot process part (not library) files, so if they are included in the entry points, the task fails. Could the analyze task filter out parts automagically?

**Comment by evanweible-wf** [comment]
@timmccall-wf the analyze task's entry points should only point to top-level files that serve as main imports for consumers (that's what the underlying dart analyzer tool expects, as well). The task does expand directories to find all immediate children, but that's mainly intended for the `lib/` directory where it's expected that the main entry points would live. I suppose the analyze task _could_ filter out `part of` files, but it seems to me like it could be fixed via the task's configuration being more explicit.

Could you point me to an example repo where this is happening?
